version: '3'
services:
  dynamo:    
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lucasbanunes/dynamo
    container_name: dynamo
    tty: true
    volumes:
      - ./:/root/dynamo
    ports:
      - "8888:8888"